# KoopmanAE.yaml

# Dataset
dataset: heat1d
batch_size: 32
input_steps: 10
output_steps: 10
normalize: true
num_workers: 4
stride: 1

# Model
model:
  latent_dim: 32
  hidden_dims_encoder: [64, 128, 256]
  hidden_dims_decoder: [256, 128, 64]
  activation: relu
  operator_type: linear
  use_batch_norm: true
  dropout: 0.1

# Loss
loss:
  recon_weight: 1.0
  pred_weight: 1.0
  physics_weight: 0.1
  linearity_weight: 0.01
  type: mse
  time_decay: 0.9

# Training
n_epochs: 100
learning_rate: 0.001
gradient_clip: 1.0

# Optimizer
optimizer:
  name: Adam  # Adam, AdamW, SGD

# Learning rate scheduler
lr_scheduler:
  name: StepLR  # StepLR, CosineAnnealingLR, ReduceLROnPlateau
  # For StepLR:
  step_size: 50
  gamma: 0.97

# Physics parameters (dataset-specific)
# These will be set automatically based on dataset